id: A4EC1BC44
title: 'Treasury of Supreme Blessings: A Guru Yoga'
type: translation
pechas:
- I6BBFBF3A
- I62DBA74B
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:51:20.126827
  last_modified_at: 2023-01-04 11:51:20.126838
  collections:
  - Fifteenth Karmapa Series
  - Works of Tibetan Masters
alignment_to_base:
  I6BBFBF3A/140E: '3344'
  I62DBA74B/0EF0: '3344'
